INSERT INTO EBOOK.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (13.2, 'Added EBOOK_DEFINITION.FRONT_MATTER_THEME column. Added EBOOK_AUDIT.FRONT_MATTER_THEME column', TO_DATE('03/20/2015', 'MM/DD/YYYY'));

ALTER TABLE EBOOK.EBOOK_DEFINITION ADD (FRONT_MATTER_THEME  VARCHAR2(100 BYTE)   DEFAULT 'WestLaw Next'  NOT NULL);
ALTER TABLE EBOOK.EBOOK_AUDIT ADD (FRONT_MATTER_THEME  VARCHAR2(100 BYTE));