INSERT INTO EBOOK.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (3.2, 'Dropped foreign key from EBOOK_AUDIT table to EBOOK_DEFINITION. Added EBOOK_DEFINITION.ADDITIONAL_TRADEMARK_INFO column. Added EBOOK_AUDIT.ADDITIONAL_TRADEMARK_INFO column. Changed EBOOK_DEFINITION.COPYRIGHT, EBOOK_DEFINITION.COPYRIGHT_PAGE_TEXT and EBOOK_DEFINITION.CURRENCY from Varchar2(1024) to Varchar2(2048). Changed EBOOK_AUDIT.COPYRIGHT, EBOOK_AUDIT.COPYRIGHT_PAGE_TEXT , EBOOK_AUDIT.CURRENCY,  EBOOK_AUDIT.AUTHOR_NAMES_CONCAT and EBOOK_AUDIT.BOOK_NAMES_CONCAT from Varchar2(1024) to Varchar2(2048). Changed AUTHOR.AUTHOR_ADDL_TEXT from Varchar2(1024) to Varchar2(2048). Changed EBOOK_NAME.BOOK_NAME_TEXT from Varchar2(1024) to Varchar2(2048).', TO_DATE('04/11/2012', 'MM/DD/YYYY'));

COMMIT;

ALTER TABLE EBOOK.EBOOK_AUDIT
  DROP CONSTRAINT AUDIT_FK1;
  
ALTER TABLE EBOOK.EBOOK_DEFINITION
MODIFY(COPYRIGHT VARCHAR2(2048 BYTE));

ALTER TABLE EBOOK.EBOOK_DEFINITION
MODIFY(COPYRIGHT_PAGE_TEXT VARCHAR2(2048 BYTE));


ALTER TABLE EBOOK.EBOOK_DEFINITION
MODIFY(CURRENCY VARCHAR2(2048 BYTE));


ALTER TABLE EBOOK.EBOOK_DEFINITION
 ADD (ADDITIONAL_TRADEMARK_INFO  VARCHAR2(2048 BYTE));

ALTER TABLE EBOOK.EBOOK_AUDIT
MODIFY(COPYRIGHT VARCHAR2(2048 BYTE));


ALTER TABLE EBOOK.EBOOK_AUDIT
MODIFY(COPYRIGHT_PAGE_TEXT VARCHAR2(2048 BYTE));


ALTER TABLE EBOOK.EBOOK_AUDIT
MODIFY(CURRENCY VARCHAR2(2048 BYTE));


ALTER TABLE EBOOK.EBOOK_AUDIT
MODIFY(AUTHOR_NAMES_CONCAT VARCHAR2(2048 BYTE));


ALTER TABLE EBOOK.EBOOK_AUDIT
MODIFY(BOOK_NAMES_CONCAT VARCHAR2(2048 BYTE));


ALTER TABLE EBOOK.EBOOK_AUDIT
 ADD (ADDITIONAL_TRADEMARK_INFO  VARCHAR2(2048 BYTE));
 
ALTER TABLE EBOOK.AUTHOR
MODIFY(AUTHOR_ADDL_TEXT VARCHAR2(2048 BYTE));

ALTER TABLE EBOOK.EBOOK_NAME
MODIFY(BOOK_NAME_TEXT VARCHAR2(2048 BYTE));