ALTER TABLE EBOOK.EBOOK_DEFINITION
 ADD (INCLUDE_NOTES_OF_DECISIONS CHAR(1 BYTE) DEFAULT 'N' NOT NULL);

ALTER TABLE EBOOK.EBOOK_AUDIT
 ADD (INCLUDE_NOTES_OF_DECISIONS CHAR(1 BYTE));
 
INSERT INTO EBOOK.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (16, 'Updated EBOOK_DEFINITION and EBOOK_AUDIT added INCLUDE_NOTES_OF_DECISIONS', TO_DATE('11/30/2016', 'MM/DD/YYYY'));

COMMIT;