ALTER TABLE EBOOK_TEST.EBOOK_DEFINITION
ADD IN_INS_STYLE_FLAG char(1) DEFAULT 'N' NOT NULL;

ALTER TABLE EBOOK_TEST.EBOOK_AUDIT
ADD IN_INS_STYLE_FLAG char(1);

ALTER TABLE EBOOK_TEST.EBOOK_DEFINITION
ADD IN_DEL_STYLE_FLAG char(1) DEFAULT 'N' NOT NULL;

ALTER TABLE EBOOK_TEST.EBOOK_AUDIT
ADD IN_DEL_STYLE_FLAG char(1);

ALTER TABLE EBOOK_TEST.EBOOK_DEFINITION
ADD IS_REMOVE_EDNOTE_HEAD_FLAG char(1) DEFAULT 'N' NOT NULL;

ALTER TABLE EBOOK_TEST.EBOOK_AUDIT
ADD IS_REMOVE_EDNOTE_HEAD_FLAG char(1);

COMMIT;
