ALTER TABLE EBOOK_QA.EBOOK_DEFINITION
ADD SOURCE_TYPE varchar2(10) DEFAULT 'TOC' NOT NULL;

ALTER TABLE EBOOK_QA.EBOOK_AUDIT
ADD SOURCE_TYPE varchar2(10);

ALTER TABLE EBOOK_QA.EBOOK_DEFINITION
ADD CWB_BOOK_NAME varchar2(1028);

ALTER TABLE EBOOK_QA.EBOOK_AUDIT
ADD CWB_BOOK_NAME varchar2(1028);

UPDATE EBOOK_QA.EBOOK_DEFINITION book
SET book.SOURCE_TYPE = 'TOC'
where book.IS_TOC_FLAG = 'Y';

UPDATE EBOOK_QA.EBOOK_DEFINITION book
SET book.SOURCE_TYPE = 'NORT'
where book.IS_TOC_FLAG = 'N';

--------------------------------------------------------
--------------------------------------------------------

CREATE TABLE EBOOK_QA.NORT_FILE_LOCATION
(
  NORT_FILE_LOCATION_ID  NUMBER               NOT NULL,
  EBOOK_DEFINITION_ID      NUMBER               NOT NULL,
  LOCATION_NAME          VARCHAR2(1024 BYTE) NOT NULL,
  SEQUENCE_NUMBER          NUMBER NOT NULL,
);

CREATE INDEX EBOOK_QA.IDX_NORT_FILE_EBOOK_DEF_ID ON EBOOK_QA.NORT_FILE_LOCATION
(EBOOK_DEFINITION_ID);

CREATE UNIQUE INDEX EBOOK_QA.PK_NORT_FILE_LOCATION ON EBOOK_QA.NORT_FILE_LOCATION
(NORT_FILE_LOCATION_ID);


ALTER TABLE EBOOK_QA.NORT_FILE_LOCATION ADD (
  CONSTRAINT PK_NORT_FILE_LOCATION
  PRIMARY KEY
  (NORT_FILE_LOCATION_ID)
  USING INDEX EBOOK_QA.PK_NORT_FILE_LOCATION
  ENABLE VALIDATE);


GRANT SELECT ON EBOOK_QA.NORT_FILE_LOCATION TO EBOOK_QA_READ;

GRANT DELETE, INSERT, SELECT, UPDATE ON EBOOK_QA.NORT_FILE_LOCATION TO EBOOK_QA_USER;

CREATE OR REPLACE SYNONYM EBOOK_QA_USER.NORT_FILE_LOCATION FOR EBOOK_QA.NORT_FILE_LOCATION;

ALTER TABLE EBOOK_QA.EBOOK_AUDIT
ADD NORT_FILE_LOCATION_CONCAT varchar2(2048);

----------------------------------------------------------
----------------------------------------------------------

CREATE SEQUENCE EBOOK_QA.NORT_FILE_LOCATION_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


GRANT SELECT ON EBOOK_QA.NORT_FILE_LOCATION_ID_SEQ TO EBOOK_QA_USER;

CREATE OR REPLACE SYNONYM EBOOK_QA_USER.NORT_FILE_LOCATION_ID_SEQ FOR EBOOK_QA.NORT_FILE_LOCATION_ID_SEQ;

COMMIT;