INSERT INTO EBOOK_CONFIG_TEST.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (2.1, 'The APP_PARAMETER.PARAMETER_VALUE column was made nullable.', TO_DATE('05/08/2012', 'MM/DD/YYYY'));

COMMIT;

ALTER TABLE EBOOK_CONFIG_TEST.APP_PARAMETER
MODIFY(PARAMETER_VALUE  NULL);