INSERT INTO EBOOK_TEST.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (14.0, 'Added SPLIT_DOCUMENT table. Added EBOOK_AUDIT.SPLIT_DOCUMENT_CONCAT, EBOOK_AUDIT.IS_SPLIT_BOOK, EBOOK_AUDIT.IS_SPLIT_TYPE_AUTO, EBOOK_AUDIT.SPLIT_EBOOK_PARTS
and EBOOK_DEFINITION.IS_SPLIT_BOOK, EBOOK_DEFINITION.IS_SPLIT_TYPE_AUTO, EBOOK_DEFINITION.SPLIT_EBOOK_PARTS columns', TO_DATE('04/21/2015', 'MM/DD/YYYY'));

COMMIT;

-- Add column to EBOOK_TEST.BOOK_DEFINITION

ALTER TABLE EBOOK_TEST.EBOOK_DEFINITION ADD (IS_SPLIT_BOOK  CHAR(1 BYTE) DEFAULT 'N' NOT NULL);
ALTER TABLE EBOOK_TEST.EBOOK_DEFINITION ADD (IS_SPLIT_TYPE_AUTO  CHAR(1 BYTE) DEFAULT 'Y' NOT NULL);
ALTER TABLE EBOOK_TEST.EBOOK_DEFINITION ADD (SPLIT_EBOOK_PARTS  NUMBER  );

ALTER TABLE EBOOK_TEST.EBOOK_AUDIT
 ADD (IS_SPLIT_BOOK  CHAR(1 BYTE));
 ALTER TABLE EBOOK_TEST.EBOOK_AUDIT
 ADD (IS_SPLIT_TYPE_AUTO  CHAR(1 BYTE));
  ALTER TABLE EBOOK_TEST.EBOOK_AUDIT
 ADD (SPLIT_EBOOK_PARTS   NUMBER);

-- Table EBOOK_TEST.SPLIT_DOCUMENT

CREATE TABLE "EBOOK_TEST"."SPLIT_DOCUMENT"(
  EBOOK_DEFINITION_ID Number NOT NULL,
  TOC_GUID Varchar2(33 ) NOT NULL,
  NOTE Varchar2(512 ) NOT NULL
);


-- Add keys for table EBOOK_TEST.SPLIT_DOCUMENT

ALTER TABLE EBOOK_TEST.SPLIT_DOCUMENT ADD CONSTRAINT SPLIT_DOCUMENT_PK PRIMARY KEY (TOC_GUID,EBOOK_DEFINITION_ID);


CREATE INDEX EBOOK_TEST.IX_SPLIT_DOCUMENT_FK ON EBOOK_TEST.SPLIT_DOCUMENT (EBOOK_DEFINITION_ID);


ALTER TABLE EBOOK_TEST.SPLIT_DOCUMENT ADD CONSTRAINT SPLIT_DOCUMENT_FK FOREIGN KEY (EBOOK_DEFINITION_ID) REFERENCES EBOOK_TEST.EBOOK_DEFINITION (EBOOK_DEFINITION_ID);

/
ALTER TABLE EBOOK_TEST.EBOOK_AUDIT
 ADD (SPLIT_DOCUMENTS_CONCAT  VARCHAR2(2048 BYTE));
 
GRANT DELETE, INSERT, SELECT, UPDATE ON EBOOK_TEST.SPLIT_DOCUMENT TO EBOOK_TEST_USER;
 
CREATE OR REPLACE SYNONYM EBOOK_TEST_USER.SPLIT_DOCUMENT FOR EBOOK_TEST.SPLIT_DOCUMENT;

COMMIT;

-- Map doc to images

INSERT INTO EBOOK_TEST.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (14.1, 'Added EBOOK_AUTHORITY_TEST.DOC_UUID columns', TO_DATE('05042015', 'MMDDYYYY'));

ALTER TABLE EBOOK_AUTHORITY_TEST.IMAGE_METADATA ADD (DOC_UUID Varchar2(36 ));

ALTER TABLE EBOOK_AUTHORITY_TEST.IMAGE_METADATA DROP CONSTRAINT IMAGE_METADATA_PK;

update EBOOK_AUTHORITY_TEST.IMAGE_METADATA set DOC_UUID='PAST BOOK';

alter table EBOOK_AUTHORITY_TEST.IMAGE_METADATA modify DOC_UUID  Varchar2(36 ) NOT NULL;

ALTER TABLE EBOOK_AUTHORITY_TEST.IMAGE_METADATA ADD CONSTRAINT IMAGE_METADATA_PK
PRIMARY KEY (JOB_INSTANCE_ID,IMAGE_GUID, DOC_UUID);

--Metadata Authority

INSERT INTO EBOOK_TEST.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (14.2, 'Added EBOOK_AUTHORITY_TEST.DOC_SIZE,EBOOK_AUTHORITY_TEST.SPLIT_BOOK_TITLE_ID columns', TO_DATE('05112015', 'MMDDYYYY'));


ALTER TABLE EBOOK_AUTHORITY_TEST.DOCUMENT_METADATA ADD (DOC_SIZE  NUMBER);
ALTER TABLE EBOOK_AUTHORITY_TEST.DOCUMENT_METADATA ADD (SPLIT_BOOK_TITLE_ID  VARCHAR2(64));

--Lock
INSERT INTO EBOOK_TEST.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (14.3, 'Added EBOOK_DEFINITION_TEST.IS_SPLIT_LOCK column', TO_DATE('05112015', 'MMDDYYYY'));

ALTER TABLE EBOOK_TEST.EBOOK_DEFINITION ADD (IS_SPLIT_LOCK  CHAR(1 BYTE) DEFAULT 'Y' NOT NULL);

-- Tracking split nodes for notes migration
INSERT INTO EBOOK_TEST.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (14.4, 'Added SPLIT_NODE_INFO table.', TO_DATE('08072015', 'MMDDYYYY'));

COMMIT;

CREATE TABLE "EBOOK_TEST"."SPLIT_NODE_INFO"(
  EBOOK_DEFINITION_ID Number NOT NULL,
  BOOK_VERSION_SUBMITTED Varchar2(10 ) NOT NULL,
  SPLIT_BOOK_TITLE_ID VARCHAR2(64 BYTE) NOT NULL, 
  SPLIT_NODE_GUID Varchar2(33 ) NOT NULL
);


ALTER TABLE EBOOK_TEST.SPLIT_NODE_INFO ADD CONSTRAINT SPLIT_NODE_INFO_PK PRIMARY KEY (EBOOK_DEFINITION_ID,BOOK_VERSION_SUBMITTED,SPLIT_BOOK_TITLE_ID);


CREATE INDEX EBOOK_TEST.IX_SPLIT_NODE_INFO_FK ON EBOOK_TEST.SPLIT_NODE_INFO (EBOOK_DEFINITION_ID);


ALTER TABLE EBOOK_TEST.SPLIT_NODE_INFO ADD CONSTRAINT SPLIT_NODE_INFO_FK FOREIGN KEY (EBOOK_DEFINITION_ID) REFERENCES EBOOK_TEST.EBOOK_DEFINITION (EBOOK_DEFINITION_ID);

GRANT DELETE, INSERT, SELECT, UPDATE ON EBOOK_TEST.SPLIT_NODE_INFO TO EBOOK_TEST_USER;
 
CREATE OR REPLACE SYNONYM EBOOK_TEST_USER.SPLIT_NODE_INFO FOR EBOOK_TEST.SPLIT_NODE_INFO;


--- Adding group version
INSERT INTO EBOOK_TEST.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (14.5, 'Added PUBLISHING_STATS.GROUP_VERSION columns.', TO_DATE('08/24/2015', 'MM/DD/YYYY'));

ALTER TABLE EBOOK_TEST.PUBLISHING_STATS
 ADD (GROUP_VERSION  NUMBER);

COMMIT;

