INSERT INTO EBOOK_CONFIG_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (2.0, 'Added APP_PARAMETER table.', TO_DATE('05/03/2012', 'MM/DD/YYYY'));

COMMIT;

-- Table APP_PARAMETER

CREATE TABLE EBOOK_CONFIG_QA."APP_PARAMETER"(
  "PARAMETER_KEY" Varchar2(128 ) NOT NULL,
  "PARAMETER_VALUE" Varchar2(1024 ) NOT NULL,
  "LAST_UPDATED" Timestamp(6) DEFAULT SYSDATE NOT NULL
)
/

-- Add keys for table APP_PARAMETER

ALTER TABLE EBOOK_CONFIG_QA."APP_PARAMETER" ADD CONSTRAINT "PK_APP_PARAMETER" PRIMARY KEY ("PARAMETER_KEY")
/

EXEC EBOOK_CONFIG_QA.GRANT_PRIVILEGES;