INSERT INTO EBOOK.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (13.1, 'Add columns IS_INS_STYLE_FLAG, IS_DEL_STYLE_FLAG, and IS_REMOVE_EDNOTE_HEAD_FLAG to EBOOK_DEFINITION and EBOOK_AUDIT', TO_DATE('1/26/2015', 'MM/DD/YYYY'));

ALTER TABLE EBOOK.EBOOK_DEFINITION
ADD IS_INS_STYLE_FLAG char(1) DEFAULT 'N' NOT NULL;

ALTER TABLE EBOOK.EBOOK_AUDIT
ADD IS_INS_STYLE_FLAG char(1);

ALTER TABLE EBOOK.EBOOK_DEFINITION
ADD IS_DEL_STYLE_FLAG char(1) DEFAULT 'N' NOT NULL;

ALTER TABLE EBOOK.EBOOK_AUDIT
ADD IS_DEL_STYLE_FLAG char(1);

ALTER TABLE EBOOK.EBOOK_DEFINITION
ADD IS_REMOVE_EDNOTE_HEAD_FLAG char(1) DEFAULT 'N' NOT NULL;

ALTER TABLE EBOOK.EBOOK_AUDIT
ADD IS_REMOVE_EDNOTE_HEAD_FLAG char(1);

COMMIT;
