INSERT INTO EBOOK_TEST.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (5.0, 'Added EXCLUDE_DOCUMENT table. Added EBOOK_AUDIT.EXCLUDED_DOCUMENTS_CONCAT column. Added JOB_HISTORY table. Added PUBLISHING_STATS.BOOK_SIZE, PUBLISHING_STATS.LARGEST_DOC_SIZE, PUBLISHING_STATS.LARGEST_IMAGE_SIZE and PUBLISHING_STATS.LARGEST_PDF_SIZE columns.', TO_DATE('05/10/2012', 'MM/DD/YYYY'));

COMMIT;

-- Table EBOOK_TEST.EXCLUDE_DOCUMENT

CREATE TABLE "EBOOK_TEST"."EXCLUDE_DOCUMENT"(
  "EBOOK_DEFINITION_ID" Number NOT NULL,
  "DOCUMENT_GUID" Varchar2(33 ) NOT NULL,
  "NOTE" Varchar2(512 ) NOT NULL,
  "LAST_UPDATED" Timestamp(6) DEFAULT SYSDATE NOT NULL
)
/

-- Add keys for table EBOOK_TEST.EXCLUDE_DOCUMENT

ALTER TABLE "EBOOK_TEST"."EXCLUDE_DOCUMENT" ADD CONSTRAINT "PK_EXCLUDE_DOCUMENT" PRIMARY KEY ("EBOOK_DEFINITION_ID","DOCUMENT_GUID")
/

CREATE INDEX "EBOOK_TEST"."IX_EXCLUDE_DOCUMENT_FK" ON "EBOOK_TEST"."EXCLUDE_DOCUMENT" ("EBOOK_DEFINITION_ID") 
/
ALTER TABLE "EBOOK_TEST"."EXCLUDE_DOCUMENT" ADD CONSTRAINT "EXCLUDE_DOCUMENT_FK" FOREIGN KEY ("EBOOK_DEFINITION_ID") REFERENCES "EBOOK_TEST"."EBOOK_DEFINITION" ("EBOOK_DEFINITION_ID")
/

ALTER TABLE EBOOK_TEST.EBOOK_AUDIT
 ADD (EXCLUDED_DOCUMENTS_CONCAT  VARCHAR2(2048 BYTE));
 
-- Table EBOOK_TEST.JOB_HISTORY

CREATE TABLE "EBOOK_TEST"."JOB_HISTORY"(
  "STEP_EXECUTION_ID" Number NOT NULL,
  "STEP_NAME" Varchar2(100 ) NOT NULL,
  "JOB_INSTANCE_ID" Number NOT NULL,
  "JOB_EXECUTION_ID" Number NOT NULL,
  "STEP_START_TIME" Timestamp(6),
  "STEP_END_TIME" Timestamp(6),
  "STEP_EXIT_CODE" Varchar2(20 ),
  "STEP_EXIT_MESSAGE" Varchar2(2500 )
)
/

-- Add keys for table EBOOK_TEST.JOB_HISTORY

ALTER TABLE "EBOOK_TEST"."JOB_HISTORY" ADD CONSTRAINT "PK_JOB_HISTORY" PRIMARY KEY ("STEP_EXECUTION_ID")
/

ALTER TABLE EBOOK_TEST.PUBLISHING_STATS
 ADD (BOOK_SIZE  NUMBER);

ALTER TABLE EBOOK_TEST.PUBLISHING_STATS
 ADD (LARGEST_DOC_SIZE  NUMBER);

ALTER TABLE EBOOK_TEST.PUBLISHING_STATS
 ADD (LARGEST_IMAGE_SIZE  NUMBER);

ALTER TABLE EBOOK_TEST.PUBLISHING_STATS
 ADD (LARGEST_PDF_SIZE  NUMBER);
 
EXEC EBOOK_TEST.GRANT_PRIVILEGES; 

COMMIT;