INSERT INTO EBOOK_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (7.0, 'Added PROVIEW_AUDIT table.', TO_DATE('06/07/2012', 'MM/DD/YYYY'));

COMMIT;

-- Table EBOOK_QA.PROVIEW_AUDIT

CREATE TABLE "EBOOK_QA"."PROVIEW_AUDIT"(
  "PROVIEW_AUDIT_ID" Number NOT NULL,
  "TITLE_ID" Varchar2(40 ) NOT NULL,
  "BOOK_VERSION" Varchar2(10 ) NOT NULL,
  "BOOK_LAST_UPDATED" Timestamp(6) NOT NULL,
  "USER_NAME" Varchar2(1024 ) NOT NULL,
  "PROVIEW_REQUEST" Varchar2(128 ) NOT NULL,
  "REQUEST_DATE" Timestamp(6) NOT NULL,
  "AUDIT_NOTE" Varchar2(1024 )
)
/

-- Add keys for table EBOOK_QA.PROVIEW_AUDIT

ALTER TABLE "EBOOK_QA"."PROVIEW_AUDIT" ADD CONSTRAINT "PK_PROVIEW_AUDIT" PRIMARY KEY ("PROVIEW_AUDIT_ID")
/

CREATE SEQUENCE "EBOOK_QA"."PROVIEW_AUDIT_ID_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20
/

EXEC EBOOK_QA.GRANT_PRIVILEGES;

COMMIT;