INSERT INTO EBOOK.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (3.1, 'Made FRONT_MATTER_SECTION.SECTION_TEXT nullable. Added FRONT_MATTER_PDF.SEQUENCE_NUMBER column. Modified EBOOK_AUDIT.FRONT_MATTER_CONCAT column from Varchar2(1024) to Clob.', TO_DATE('04/04/2012', 'MM/DD/YYYY'));
COMMIT;

ALTER TABLE EBOOK.FRONT_MATTER_SECTION MODIFY(SECTION_TEXT  NULL);
ALTER TABLE EBOOK.EBOOK_AUDIT DROP COLUMN FRONT_MATTER_CONCAT;
ALTER TABLE EBOOK.EBOOK_AUDIT ADD (FRONT_MATTER_CONCAT  CLOB);
ALTER TABLE EBOOK.FRONT_MATTER_PDF ADD (SEQUENCE_NUMBER  NUMBER  DEFAULT 1);