INSERT INTO EBOOK_AUTHORITY_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
 VALUES (3.3, 'Added DOCUMENT_METADATA.FIRSTLINE_CITE_PUBPAGE, DOCUMENT_METADATA.FIRSTLINE_CITE_PUB_ID, DOCUMENT_METADATA.SECONDLINE_CITE_PUB_ID, and DOCUMENT_METADATA.THIRDLINE_CITE_PUB_ID columns.', TO_DATE('09/25/2012', 'MM/DD/YYYY'));
COMMIT;

ALTER TABLE EBOOK_AUTHORITY_QA.DOCUMENT_METADATA 
 ADD (FIRSTLINE_CITE_PUBPAGE Varchar2(512 ));
	
ALTER TABLE EBOOK_AUTHORITY_QA.DOCUMENT_METADATA 
 ADD (FIRSTLINE_CITE_PUB_ID NUMBER);

ALTER TABLE EBOOK_AUTHORITY_QA.DOCUMENT_METADATA 
 ADD (SECONDLINE_CITE_PUB_ID NUMBER);
 
ALTER TABLE EBOOK_AUTHORITY_QA.DOCUMENT_METADATA 
 ADD (THIRDLINE_CITE_PUB_ID NUMBER);