INSERT INTO EBOOK_CONFIG_TEST.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (3.0, 'Added new Planned Outage tables.', TO_DATE('05/24/2012', 'MM/DD/YYYY'));

COMMIT;

-- Table PLANNED_OUTAGE

CREATE TABLE "EBOOK_CONFIG_TEST"."PLANNED_OUTAGE"(
  "OUTAGE_ID" Number NOT NULL,
  "OUTAGE_TYPE_ID" Number NOT NULL,
  "START_TIME" Timestamp(6) NOT NULL,
  "END_TIME" Timestamp(6) NOT NULL,
  "REASON" Varchar2(2048 ) NOT NULL,
  "SYSTEM_IMPACT_DESCRIPTION" Varchar2(2048 ),
  "SERVERS_IMPACTED" Varchar2(2048 ),
  "NOTIFICATION_EMAIL_SENT" Char(1 ),
  "ALL_CLEAR_EMAIL_SENT" Char(1 ),
  "UPDATED_BY" Varchar2(128 ) NOT NULL,
  "LAST_UPDATED" Timestamp(6) DEFAULT SYSTIMESTAMP NOT NULL
)
/

-- Add keys for table PLANNED_OUTAGE

ALTER TABLE "EBOOK_CONFIG_TEST"."PLANNED_OUTAGE" ADD CONSTRAINT "PK_PLANNED_OUTAGE" PRIMARY KEY ("OUTAGE_ID")
/

-- Table EBOOK_CONFIG_TEST.OUTAGE_TYPE

CREATE TABLE "EBOOK_CONFIG_TEST"."OUTAGE_TYPE"(
  "OUTAGE_TYPE_ID" Number NOT NULL,
  "SYSTEM" Varchar2(128 ) NOT NULL,
  "SUB_SYSTEM" Varchar2(128 ) NOT NULL,
  "LAST_UPDATED" Timestamp(6) DEFAULT SYSTIMESTAMP NOT NULL
)
/

-- Add keys for table EBOOK_CONFIG_TEST.OUTAGE_TYPE

ALTER TABLE "EBOOK_CONFIG_TEST"."OUTAGE_TYPE" ADD CONSTRAINT "PK_OUTAGE_TYPE" PRIMARY KEY ("OUTAGE_TYPE_ID")
/

ALTER TABLE "EBOOK_CONFIG_TEST"."PLANNED_OUTAGE" ADD CONSTRAINT "REL_1" FOREIGN KEY ("OUTAGE_TYPE_ID") REFERENCES "EBOOK_CONFIG_TEST"."OUTAGE_TYPE" ("OUTAGE_TYPE_ID")
/

CREATE SEQUENCE "EBOOK_CONFIG_TEST"."OUTAGE_ID_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20
/

CREATE SEQUENCE "EBOOK_CONFIG_TEST"."OUTAGE_TYPE_ID_SEQ"
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 NOMINVALUE
 CACHE 20
/

EXEC EBOOK_CONFIG_TEST.GRANT_PRIVILEGES;

COMMIT;