INSERT INTO EBOOK_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (14.0, 'Added SPLIT_DOCUMENT table. Added EBOOK_AUDIT.SPLIT_DOCUMENT_CONCAT, EBOOK_AUDIT.IS_SPLIT_BOOK, EBOOK_AUDIT.IS_SPLIT_TYPE_AUTO, EBOOK_AUDIT.SPLIT_EBOOK_PARTS
and EBOOK_DEFINITION.IS_SPLIT_BOOK, EBOOK_DEFINITION.IS_SPLIT_TYPE_AUTO, EBOOK_DEFINITION.SPLIT_EBOOK_PARTS columns', TO_DATE('04212015', 'MMDDYYYY'));

COMMIT;

-- Add column to EBOOK_QA.BOOK_DEFINITION

ALTER TABLE EBOOK_QA.EBOOK_DEFINITION ADD (IS_SPLIT_BOOK  CHAR(1 BYTE) DEFAULT 'N' NOT NULL);
ALTER TABLE EBOOK_QA.EBOOK_DEFINITION ADD (IS_SPLIT_TYPE_AUTO  CHAR(1 BYTE) DEFAULT 'Y' NOT NULL);
ALTER TABLE EBOOK_QA.EBOOK_DEFINITION ADD (SPLIT_EBOOK_PARTS  NUMBER  );

ALTER TABLE EBOOK_QA.EBOOK_AUDIT
 ADD (IS_SPLIT_BOOK  CHAR(1 BYTE));
 ALTER TABLE EBOOK_QA.EBOOK_AUDIT
 ADD (IS_SPLIT_TYPE_AUTO  CHAR(1 BYTE));
  ALTER TABLE EBOOK_QA.EBOOK_AUDIT
 ADD (SPLIT_EBOOK_PARTS  NUMBER);

-- Table EBOOK_QA.SPLIT_DOCUMENT

CREATE TABLE "EBOOK_QA"."SPLIT_DOCUMENT"(
  EBOOK_DEFINITION_ID Number NOT NULL,
  TOC_GUID Varchar2(33 ) NOT NULL,
  NOTE Varchar2(512 ) NOT NULL
);


-- Add keys for table EBOOK_QA.SPLIT_DOCUMENT

ALTER TABLE EBOOK_QA.SPLIT_DOCUMENT ADD CONSTRAINT SPLIT_DOCUMENT_PK PRIMARY KEY (TOC_GUID,EBOOK_DEFINITION_ID);


CREATE INDEX EBOOK_QA.IX_SPLIT_DOCUMENT_FK ON EBOOK.SPLIT_DOCUMENT (EBOOK_DEFINITION_ID);


ALTER TABLE EBOOK_QA.SPLIT_DOCUMENT ADD CONSTRAINT SPLIT_DOCUMENT_FK FOREIGN KEY (EBOOK_DEFINITION_ID) REFERENCES EBOOK.EBOOK_DEFINITION (EBOOK_DEFINITION_ID);


ALTER TABLE EBOOK_QA.EBOOK_AUDIT
 ADD (SPLIT_DOCUMENTS_CONCAT  VARCHAR2(2048 BYTE));
 
GRANT DELETE, INSERT, SELECT, UPDATE ON EBOOK_QA.SPLIT_DOCUMENT TO EBOOK_QA_USER;
 
CREATE OR REPLACE SYNONYM EBOOK_QA_USER.SPLIT_DOCUMENT FOR EBOOK_QA.SPLIT_DOCUMENT;

COMMIT;

-- Map doc to images

INSERT INTO EBOOK_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (14.1, 'Added EBOOK_AUTHORITY_QA.DOC_UUID columns', TO_DATE('05042015', 'MMDDYYYY'));

ALTER TABLE EBOOK_AUTHORITY_QA.IMAGE_METADATA ADD (DOC_UUID Varchar2(36 ));

ALTER TABLE EBOOK_AUTHORITY_QA.IMAGE_METADATA DROP CONSTRAINT IMAGE_METADATA_PK;

update EBOOK_AUTHORITY_QA.IMAGE_METADATA set DOC_UUID="PAST BOOK";

alter table EBOOK_AUTHORITY_QA.IMAGE_METADATA modify DOC_UUID  Varchar2(36 ) NOT NULL;

ALTER TABLE EBOOK_AUTHORITY_QA.IMAGE_METADATA ADD CONSTRAINT IMAGE_METADATA_PK
PRIMARY KEY (JOB_INSTANCE_ID,IMAGE_GUID, DOC_UUID);