INSERT INTO EBOOK_AUTHORITY.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (2.0, 'Made DOCUMENT_METADATA.DOC_FAMILY_UUID nullable. Added IMAGE_METADATA.MEDIA_TYPE column. Added CAS_TICKET_REGISTRY table.', TO_DATE('02/16/2012', 'MM/DD/YYYY'));

COMMIT;

ALTER TABLE EBOOK_AUTHORITY.DOCUMENT_METADATA
MODIFY(DOC_FAMILY_UUID  NULL);

ALTER TABLE EBOOK_AUTHORITY.IMAGE_METADATA
 ADD (MEDIA_TYPE  VARCHAR2(64 BYTE));

-- Table EBOOK_AUTHORITY.CAS_TICKET_REGISTRY

CREATE TABLE "EBOOK_AUTHORITY"."CAS_TICKET_REGISTRY"(
  "ID" Varchar2(400 ) NOT NULL,
  "TICKET" Blob NOT NULL
)
/

-- Add keys for table EBOOK_AUTHORITY.CAS_TICKET_REGISTRY

ALTER TABLE "EBOOK_AUTHORITY"."CAS_TICKET_REGISTRY" ADD CONSTRAINT "PK_CAS_TICKET_REGISTRY" PRIMARY KEY ("ID")
/

EXEC EBOOK_AUTHORITY.GRANT_PRIVILEGES;