INSERT INTO EBOOK_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (9.0, 'Added RENAME_TOC_ENTRY table. Added EBOOK_AUDIT.RENAME_TOC_ENTRY_CONCAT column', TO_DATE('06/27/2012', 'MM/DD/YYYY'));

COMMIT;

-- Table EBOOK_QA.RENAME_TOC_ENTRY

CREATE TABLE "EBOOK_QA"."RENAME_TOC_ENTRY"(
  "EBOOK_DEFINITION_ID" Number NOT NULL,
  "TOC_GUID" Varchar2(33 ) NOT NULL,
  "OLD_LABEL" Varchar2(1024 ) NOT NULL,
  "NEW_LABEL" Varchar2(1024 ) NOT NULL,
  "NOTE" Varchar2(512 ) NOT NULL,
  "LAST_UPDATED" Timestamp(6) DEFAULT SYSDATE NOT NULL
)
/

-- Add keys for table EBOOK_QA.RENAME_TOC_ENTRY
ALTER TABLE "EBOOK_QA"."RENAME_TOC_ENTRY" ADD CONSTRAINT "RENAME_TOC_ENTRY_PK" PRIMARY KEY ("TOC_GUID","EBOOK_DEFINITION_ID")
/

CREATE INDEX "EBOOK_QA"."IX_RENAME_TOC_ENTRY_FK" ON "EBOOK_QA"."RENAME_TOC_ENTRY" ("EBOOK_DEFINITION_ID") 
/
ALTER TABLE "EBOOK_QA"."RENAME_TOC_ENTRY" ADD CONSTRAINT "RENAME_TOC_ENTRY_FK" FOREIGN KEY ("EBOOK_DEFINITION_ID") REFERENCES "EBOOK_QA"."EBOOK_DEFINITION" ("EBOOK_DEFINITION_ID")
/

ALTER TABLE EBOOK_QA.EBOOK_AUDIT
 ADD (RENAME_TOC_ENTRY_CONCAT  VARCHAR2(2048 BYTE));

EXEC EBOOK_QA.GRANT_PRIVILEGES; 

COMMIT;