INSERT INTO EBOOK.XPP_BUNDLE_ARCHIVE (
		XPP_BUNDLE_ARCHIVE_ID,
		DATE_TIME,
		MESSAGE_ID,
		MESSAGE_REQUEST,
		MATERIAL_NUMBER,
		DELETED,
		ARCHIVE_LOCATION,
		RESURRECT_COUNT)

SELECT 
		EBOOK.XPP_BUNDLE_ARCHIVE_ID_SEQ.NEXTVAL,
		DT,
		M_ID,
		M_REQUEST,
		M_NUMBER,
		DEL_FLAG,
		A_LOCATION,
		R_COUNT
		FROM ( SELECT 
			  SYSDATE DT,
			  '123456' M_ID,
			  'message request' M_REQUEST,
			  '41893032' M_NUMBER,
			  'N' DEL_FLAG,
			  '/apps/eBookBuilder/workstation/xpp/archive/bundle_CHAL.zip' A_LOCATION,
			  0 R_COUNT
			  FROM DUAL
		); 