Insert into EBOOK_TEST.DOCUMENT_TYPE_CODES
   (DOCUMENT_TYPE_CODES_ID, DOCUMENT_TYPE_CODES_ABBRV, DOCUMENT_TYPE_CODES_NAME, USE_PUBLISH_CUTOFF_DATE_FLAG, LAST_UPDATED)
 Values
   (1, 'an', 'Analytical', 'N', 
    TO_TIMESTAMP('3/5/2012 10:33:17.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.DOCUMENT_TYPE_CODES
   (DOCUMENT_TYPE_CODES_ID, DOCUMENT_TYPE_CODES_ABBRV, DOCUMENT_TYPE_CODES_NAME, USE_PUBLISH_CUTOFF_DATE_FLAG, LAST_UPDATED)
 Values
   (2, 'sc', 'Slice Codes', 'Y', 
    TO_TIMESTAMP('3/5/2012 10:48:06.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.DOCUMENT_TYPE_CODES
   (DOCUMENT_TYPE_CODES_ID, DOCUMENT_TYPE_CODES_ABBRV, DOCUMENT_TYPE_CODES_NAME, USE_PUBLISH_CUTOFF_DATE_FLAG, LAST_UPDATED)
 Values
   (3, 'cr', 'Court Rules', 'Y', 
    TO_TIMESTAMP('3/5/2012 10:48:25.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
COMMIT;

Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (1, 'AL', TO_TIMESTAMP('3/2/2012 4:11:33.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (2, 'AK', TO_TIMESTAMP('3/2/2012 4:12:23.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (3, 'AZ', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (4, 'AR', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (5, 'CA', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (6, 'CO', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (7, 'CT', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (8, 'DE', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (9, 'FL', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (10, 'GA', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (11, 'HI', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (12, 'ID', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (13, 'IL', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (14, 'IN', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (15, 'IA', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (16, 'KS', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (17, 'KY', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (18, 'LA', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (19, 'ME', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (20, 'MD', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (21, 'MA', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (22, 'MI', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (23, 'MN', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (24, 'MS', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (25, 'MO', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (26, 'MT', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (27, 'NE', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (28, 'NV', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (29, 'NH', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (30, 'NJ', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (31, 'NM', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (32, 'NY', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (33, 'NC', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (34, 'ND', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (35, 'OH', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (36, 'OK', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (37, 'OR', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (38, 'PA', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (39, 'RI', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (40, 'SC', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (41, 'SD', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (42, 'TN', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (43, 'TX', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (44, 'UT', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (45, 'VT', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (46, 'VA', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (47, 'WA', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (48, 'WV', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (49, 'WI', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (50, 'WY', TO_TIMESTAMP('3/2/2012 4:12:50.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.JURIS_TYPE_CODES
   (JURIS_TYPE_CODES_ID, JURIS_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (51, 'US', TO_TIMESTAMP('3/2/2012 4:13:17.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
COMMIT;

Insert into EBOOK_TEST.KEYWORD_TYPE_CODES
   (KEYWORD_TYPE_CODES_ID, KEYWORD_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (1, 'Jurisdiction', TO_TIMESTAMP('3/5/2012 3:33:31.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.KEYWORD_TYPE_CODES
   (KEYWORD_TYPE_CODES_ID, KEYWORD_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (2, 'Type', TO_TIMESTAMP('3/5/2012 3:34:00.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.KEYWORD_TYPE_CODES
   (KEYWORD_TYPE_CODES_ID, KEYWORD_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (3, 'Publisher', TO_TIMESTAMP('3/5/2012 3:34:00.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.KEYWORD_TYPE_CODES
   (KEYWORD_TYPE_CODES_ID, KEYWORD_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (4, 'Subject', TO_TIMESTAMP('3/5/2012 3:34:00.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
COMMIT;

Insert into EBOOK_TEST.PUB_TYPE_CODES
   (PUB_TYPE_CODES_ID, PUB_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (1, 'Local', TO_TIMESTAMP('3/2/2012 4:15:18.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.PUB_TYPE_CODES
   (PUB_TYPE_CODES_ID, PUB_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (2, 'State', TO_TIMESTAMP('3/2/2012 4:15:19.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.PUB_TYPE_CODES
   (PUB_TYPE_CODES_ID, PUB_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (3, 'Fed', TO_TIMESTAMP('3/2/2012 4:15:19.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.PUB_TYPE_CODES
   (PUB_TYPE_CODES_ID, PUB_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (4, 'FedRule', TO_TIMESTAMP('3/2/2012 4:15:19.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.PUB_TYPE_CODES
   (PUB_TYPE_CODES_ID, PUB_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (5, 'FedDist', TO_TIMESTAMP('3/2/2012 4:15:19.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.PUB_TYPE_CODES
   (PUB_TYPE_CODES_ID, PUB_TYPE_CODES_NAME, LAST_UPDATED)
 Values
   (6, 'Bankr', TO_TIMESTAMP('3/2/2012 4:15:19.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
COMMIT;

Insert into EBOOK_TEST.PUBLISHER_CODES
   (PUBLISHER_CODES_ID, PUBLISHER_NAME, LAST_UPDATED)
 Values
   (1, 'uscl', TO_TIMESTAMP('3/5/2012 10:33:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
COMMIT;

Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (1, 'AL', TO_TIMESTAMP('3/2/2012 4:01:03.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (2, 'AK', TO_TIMESTAMP('3/2/2012 4:01:03.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (3, 'AZ', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (4, 'AR', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (5, 'CA', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (6, 'CO', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (7, 'CT', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (8, 'DE', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (9, 'FL', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (10, 'GA', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (11, 'HI', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (12, 'ID', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (13, 'IL', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (14, 'IN', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (15, 'IA', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (16, 'KS', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (17, 'KY', TO_TIMESTAMP('3/2/2012 4:01:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (18, 'LA', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (19, 'ME', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (20, 'MD', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (21, 'MA', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (22, 'MI', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (23, 'MN', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (24, 'MS', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (25, 'MO', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (26, 'MT', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (27, 'NE', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (28, 'NV', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (29, 'NH', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (30, 'NJ', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (31, 'NM', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (32, 'NY', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (33, 'NC', TO_TIMESTAMP('3/2/2012 4:01:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (34, 'ND', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (35, 'OH', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (36, 'OK', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (37, 'OR', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (38, 'PA', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (39, 'RI', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (40, 'SC', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (41, 'SD', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (42, 'TN', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (43, 'TX', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (44, 'UT', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (45, 'VT', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (46, 'VA', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (47, 'WA', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (48, 'WV', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (49, 'WI', TO_TIMESTAMP('3/2/2012 4:01:06.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into EBOOK_TEST.STATE_CODES
   (STATE_CODES_ID, STATE_CODES_NAME, LAST_UPDATED)
 Values
   (50, 'WY', TO_TIMESTAMP('3/2/2012 4:01:07.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
COMMIT;

AUDIT_ID_SEQ
AUTHOR_ID_SEQ;
SELECT EBOOK_TEST.DOC_TYPE_CODES_ID_SEQ.NEXTVAL FROM DUAL;
EBOOK_DEFINITION_ID_SEQ
EBOOK_NAME_ID_SEQ
FRONT_MATTER_PAGE_ID_SEQ
FRONT_MATTER_PDF_ID_SEQ
FRONT_MATTER_SECTION_ID_SEQ
JOB_REQUEST_ID_SEQ;
SELECT EBOOK_TEST.JURIS_TYPE_CODES_ID_SEQ.NEXTVAL FROM DUAL;
SELECT EBOOK_TEST.KEYWORD_TYPE_CODES_ID_SEQ.NEXTVAL FROM DUAL;
KEYWORD_TYPE_VALUES_ID_SEQ
SELECT EBOOK_TEST.PUB_TYPE_CODES_ID_SEQ.NEXTVAL FROM DUAL;
SELECT EBOOK_TEST.PUBLISHER_CODES_ID_SEQ.NEXTVAL FROM DUAL;
SELECT EBOOK_TEST.STATE_CODES_ID_SEQ.NEXTVAL FROM DUAL;