version: 0.2

env:
  variables:
    SOURCE_ZIP_FILEAME: source-artifact.zip

phases:

  # Setting up the NodeJS environment in CodeBuild
  install:
    runtime-versions:
      nodejs: 12

  build:
    commands:
      # Download NPM packages that we don't want to keep in our repo
      # Like 'npm install', but use 'package-lock.json' instead of 'package.json'
      - cd app/
      - npm ci --only=prod
      - cd ..

  post_build:
    commands:
      - zip -r ${SOURCE_ZIP_FILEAME} ./

artifacts:
  secondary-artifacts:
    BakeInput:
      files:
        - "**/*"
    BuildOutput:
      files:
        - ${SOURCE_ZIP_FILEAME}
