---

AWSTemplateFormatVersion: 2010-09-09
Description: A template that contains a "s3 publish" component for a Cumulus CICD pipeline.

Parameters:
  OutputBucket:
    Description: Name of the bucket where you want to upload the result of your build
    Type: String
  OutputObjectKey:
    Description: Key to the file in the bucket where you want to upload the result of your build to.
    Type: String

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Stages:
        # This is where a source stage would go.
        # A build stage would go here.
        - Name: BuildComponent
          Actions:
            - Name: Publish  # Use CodeDeploy S3 action to push to S3.
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: '1'
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                BucketName:
                  Fn::Ref: OutputBucket
                # We have to put 'True' since we want different builds to have different names
                # The names thus have to be generated by the build step.
                Extract: true
                ObjectKey:
                  Fn::Ref: OutputObjectKey
              RunOrder: 2
