INSERT INTO EBOOK.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (20.0, 'Updated EBOOK_AUTHORITY.IMAGE_METADATA DOC_UUID from Varchar2(50) to Varchar2(200).', TO_DATE('08/04/2017', 'MM/DD/YYYY'));

alter table EBOOK_AUTHORITY.IMAGE_METADATA modify DOC_UUID Varchar2(200);

