ALTER TABLE EBOOK.EBOOK_DEFINITION ADD (RELEASE_NOTES Varchar2(2048));

ALTER TABLE EBOOK.EBOOK_AUDIT ADD (RELEASE_NOTES Varchar2(2048));

INSERT INTO EBOOK.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (33, 'Added column RELEASE_NOTES to tables EBOOK_DEFINITION and EBOOK_AUDIT', TO_DATE('03/26/2020', 'MM/DD/YYYY'));