INSERT INTO EBOOK_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (11.0, 'Added DOCUMENT_COPYRIGHT and DOCUMENT_CURRENCY tables. Added EBOOK_AUDIT.DOCUMENT_CURRENCY_CONCAT, EBOOK_AUDIT.DOCUMENT_COPYRIGHT_CONCAT, and EBOOK_DEFINITION.IS_FINAL_STAGE columns', TO_DATE('07/23/2012', 'MM/DD/YYYY'));

COMMIT;

-- Add column to EBOOK_QA.BOOK_DEFINITION

ALTER TABLE EBOOK_QA.EBOOK_DEFINITION ADD (IS_FINAL_STAGE  CHAR(1 BYTE) DEFAULT 'Y' NOT NULL);

ALTER TABLE EBOOK_QA.EBOOK_AUDIT
 ADD (IS_FINAL_STAGE  CHAR(1 BYTE));

-- Table EBOOK_QA.DOCUMENT_COPYRIGHT

CREATE TABLE "EBOOK_QA"."DOCUMENT_COPYRIGHT"(
  "EBOOK_DEFINITION_ID" Number NOT NULL,
  "COPYRIGHT_GUID" Varchar2(33 ) NOT NULL,
  "NEW_TEXT" Varchar2(512 ) NOT NULL,
  "NOTE" Varchar2(512 ) NOT NULL,
  "LAST_UPDATED" Timestamp(6) DEFAULT SYSDATE NOT NULL
)
/

-- Add keys for table EBOOK_QA.DOCUMENT_COPYRIGHT

ALTER TABLE "EBOOK_QA"."DOCUMENT_COPYRIGHT" ADD CONSTRAINT "DOCUMENT_COPYRIGHT_PK" PRIMARY KEY ("COPYRIGHT_GUID","EBOOK_DEFINITION_ID")
/

CREATE INDEX "EBOOK_QA"."IX_DOCUMENT_COPYRIGHT_FK" ON "EBOOK_QA"."DOCUMENT_COPYRIGHT" ("EBOOK_DEFINITION_ID")
/

ALTER TABLE "EBOOK_QA"."DOCUMENT_COPYRIGHT" ADD CONSTRAINT "DOCUMENT_COPYRIGHT_FK" FOREIGN KEY ("EBOOK_DEFINITION_ID") REFERENCES "EBOOK_QA"."EBOOK_DEFINITION" ("EBOOK_DEFINITION_ID")
/

ALTER TABLE EBOOK_QA.EBOOK_AUDIT
 ADD (DOCUMENT_COPYRIGHT_CONCAT  VARCHAR2(2048 BYTE));

COMMIT;

-- Table EBOOK_QA.DOCUMENT_CURRENCY

CREATE TABLE "EBOOK_QA"."DOCUMENT_CURRENCY"(
  "EBOOK_DEFINITION_ID" Number NOT NULL,
  "CURRENCY_GUID" Varchar2(33 ) NOT NULL,
  "NEW_TEXT" Varchar2(512 ) NOT NULL,
  "NOTE" Varchar2(512 ) NOT NULL,
  "LAST_UPDATED" Timestamp(6) DEFAULT SYSDATE NOT NULL
)
/

-- Add keys for table EBOOK_QA.DOCUMENT_CURRENCY

ALTER TABLE "EBOOK_QA"."DOCUMENT_CURRENCY" ADD CONSTRAINT "DOCUMENT_CURRENCY_PK" PRIMARY KEY ("CURRENCY_GUID","EBOOK_DEFINITION_ID")
/

CREATE INDEX "EBOOK_QA"."IX_DOCUMENT_CURRENCY_FK" ON "EBOOK_QA"."DOCUMENT_CURRENCY" ("EBOOK_DEFINITION_ID")
/

ALTER TABLE "EBOOK_QA"."DOCUMENT_CURRENCY" ADD CONSTRAINT "DOCUMENT_CURRENCY_FK" FOREIGN KEY ("EBOOK_DEFINITION_ID") REFERENCES "EBOOK_QA"."EBOOK_DEFINITION" ("EBOOK_DEFINITION_ID")
/

ALTER TABLE EBOOK_QA.EBOOK_AUDIT
 ADD (DOCUMENT_CURRENCY_CONCAT  VARCHAR2(2048 BYTE));

EXEC EBOOK_QA.GRANT_PRIVILEGES;

COMMIT;
