INSERT INTO EBOOK_AUTHORITY_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (2.1, 'Added DOCUMENT_METADATA.PROVIEW_FAMILY_UUID_DEDUP column.', TO_DATE('04/26/2012', 'MM/DD/YYYY'));

COMMIT;

ALTER TABLE EBOOK_AUTHORITY_QA.DOCUMENT_METADATA
 ADD (PROVIEW_FAMILY_UUID_DEDUP  NUMBER);