INSERT INTO EBOOK_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (10.0, 'Added TABLE_VIEWER table. Added EBOOK_AUDIT.TABLE_VIEWER_CONCAT column', TO_DATE('07/09/2012', 'MM/DD/YYYY'));

COMMIT;

-- Table EBOOK_QA.TABLE_VIEWER

CREATE TABLE "EBOOK_QA"."TABLE_VIEWER"(
  "EBOOK_DEFINITION_ID" Number NOT NULL,
  "DOCUMENT_GUID" Varchar2(33 ) NOT NULL,
  "NOTE" Varchar2(512 ) NOT NULL,
  "LAST_UPDATED" Timestamp(6) DEFAULT SYSDATE NOT NULL
)
/

-- Add keys for table EBOOK_QA.TABLE_VIEWER
ALTER TABLE "EBOOK_QA"."TABLE_VIEWER" ADD CONSTRAINT "TABLE_VIEWER_PK" PRIMARY KEY ("EBOOK_DEFINITION_ID","DOCUMENT_GUID")
/

CREATE INDEX "EBOOK_QA"."IX_TABLE_VIEWER_FK" ON "EBOOK_QA"."TABLE_VIEWER" ("EBOOK_DEFINITION_ID") 
/
ALTER TABLE "EBOOK_QA"."TABLE_VIEWER" ADD CONSTRAINT "TABLE_VIEWER_FK" FOREIGN KEY ("EBOOK_DEFINITION_ID") REFERENCES "EBOOK_QA"."EBOOK_DEFINITION" ("EBOOK_DEFINITION_ID")
/

ALTER TABLE EBOOK_QA.EBOOK_AUDIT
 ADD (TABLE_VIEWER_CONCAT  VARCHAR2(2048 BYTE));

EXEC EBOOK_QA.GRANT_PRIVILEGES; 

COMMIT;