INSERT INTO EBOOK_AUTHORITY_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (3.1, 'Added DOCUMENT_METADATA.FIRSTLINE_CITE and DOCUMENT_METADATA.SECONDLINE_CITE.', TO_DATE('05/29/2012', 'MM/DD/YYYY'));

COMMIT;

ALTER TABLE EBOOK_AUTHORITY_QA.DOCUMENT_METADATA
 ADD (FIRSTLINE_CITE  VARCHAR2(128 BYTE));
 
ALTER TABLE EBOOK_AUTHORITY_QA.DOCUMENT_METADATA
 ADD (SECONDLINE_CITE  VARCHAR2(128 BYTE));
 
EXEC EBOOK_AUTHORITY_QA.GRANT_PRIVILEGES;

COMMIT;