/*
* Copyright 2011: Thomson Reuters Global Resources. All Rights Reserved.
* Proprietary and Confidential information of TRGR. Disclosure, Use or
* Reproduction without the written authorization of TRGR is prohibited
*/
package com.thomsonreuters.uscl.ereader.format.step;

import java.io.File;

import org.apache.log4j.Logger;
import org.springframework.batch.core.ExitStatus;
import org.springframework.batch.core.JobInstance;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.StepContribution;
import org.springframework.batch.core.scope.context.ChunkContext;
import org.springframework.batch.item.ExecutionContext;

import com.thomsonreuters.uscl.ereader.JobExecutionKey;
import com.thomsonreuters.uscl.ereader.JobParameterKey;
import com.thomsonreuters.uscl.ereader.core.book.domain.BookDefinition;
import com.thomsonreuters.uscl.ereader.format.exception.EBookFormatException;
import com.thomsonreuters.uscl.ereader.format.service.HTMLTransformerService;
import com.thomsonreuters.uscl.ereader.orchestrate.core.tasklet.AbstractSbTasklet;

/**
 * This step transforms the HTML generated by the transformation process into ProView acceptable HTML.
 *
 * @author <a href="mailto:Selvedin.Alic@thomsonreuters.com">Selvedin Alic</a> u0095869
 */
public class HTMLPostTransform extends AbstractSbTasklet
{
	//TODO: Use logger API to get Logger instance to job-specific appender.
	private static final Logger LOG = Logger.getLogger(HTMLPostTransform.class);
	private HTMLTransformerService transformerService;

	public void settransformerService(HTMLTransformerService transformerService) 
	{
		this.transformerService = transformerService;
	}
	
	@Override
	public ExitStatus executeStep(StepContribution contribution, ChunkContext chunkContext) throws Exception 
	{
		ExecutionContext jobExecutionContext = getJobExecutionContext(chunkContext);
		JobParameters jobParams = getJobParameters(chunkContext);
		JobInstance jobInstance = getJobInstance(chunkContext);
		
		BookDefinition bookDefinition = (BookDefinition)jobExecutionContext.get(JobExecutionKey.EBOOK_DEFINITON);
		
		String titleId = bookDefinition.getTitleId();
		Long jobId = jobInstance.getId();

		String transformDirectory = 
				getRequiredStringProperty(jobExecutionContext, JobExecutionKey.FORMAT_TRANSFORMED_DIR);
		String postTransformDirectory = 
				getRequiredStringProperty(jobExecutionContext, JobExecutionKey.FORMAT_POST_TRANSFORM_DIR);
		String staticImagePath = 
				getRequiredStringProperty(jobExecutionContext, JobExecutionKey.IMAGE_STATIC_MANIFEST_FILE);
		String docsGuid = getRequiredStringProperty(jobExecutionContext,JobExecutionKey.DOCS_DYNAMIC_GUIDS_FILE);
		
		String deDupping = getRequiredStringProperty(jobExecutionContext,JobExecutionKey.DEDUPPING_FILE);
		//TODO: Set value below based on execution context value
		int numDocsInTOC = 0; 
		
		boolean isTableViewRequired = bookDefinition.isProviewTableViewFlag();
		
		File transformDir = new File(transformDirectory);
		File postTransformDir = new File(postTransformDirectory);
		File staticImgFile = new File(staticImagePath);
		File docsGuidFile = new File(docsGuid);
		File deDuppingFile = new File(deDupping);
		
		
		long startTime = System.currentTimeMillis();
		int numDocsTransformed = 
				transformerService.transformHTML(transformDir, postTransformDir, staticImgFile, isTableViewRequired,titleId, jobId, null, docsGuidFile, deDuppingFile);
		long endTime = System.currentTimeMillis();
		long elapsedTime = endTime - startTime;
		
		//TODO: Add check to make sure number of documents that were transformed equals number of documents
		//retrieved from Novus
		if (numDocsTransformed == 0)
		{
			String message = "The number of post transformed documents did not match the number " +
					"of documents retrieved from the eBook TOC. Transformed " + numDocsTransformed + 
					" documents while the eBook TOC had " + numDocsInTOC + " documents.";
			LOG.error(message);
			throw new EBookFormatException(message);
		}
		
		//TODO: Improve metrics
		LOG.debug("Transformed " + numDocsTransformed + " HTML files in " + elapsedTime + " milliseconds");
		
		return ExitStatus.COMPLETED;
	}
}
