INSERT INTO DOCUMENT_TYPE_CODES
(
    DOCUMENT_TYPE_CODES_ID,
    DOCUMENT_TYPE_CODES_ABBRV,
    DOCUMENT_TYPE_CODES_NAME,
    USE_PUBLISH_CUTOFF_DATE_FLAG,
    THRESHOLD_VALUE,
    THRESHOLD_PERCENT,
    PUBLISHER_CODES_ID
)
VALUES
(5,'ots','One Time Sale','N', 7500, 10, 2);
COMMIT;