
--02/27/2017
--User Johnson, Durene (Legal) has requested to remove these users from ebook who are no longer worning on the project

delete from USER_PREFERENCE where EMAIL_LIST='nancy.mallo@thomsonreuters.com';
delete from USER_PREFERENCE where EMAIL_LIST='joanna.killigrew@thomsonreuters.com';
delete from USER_PREFERENCE where EMAIL_LIST='benita.greenfield@thomsonreuters.com';
delete from USER_PREFERENCE where EMAIL_LIST='kelly.cooper@thomsonreuters.com';