ALTER TABLE EBOOK_QA.JOB_REQUEST DROP COLUMN JOB_STATUS;
ALTER TABLE EBOOK_QA.JOB_REQUEST DROP COLUMN JOB_SCHEDULE_TIMESTAMP;

INSERT INTO EBOOK_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (17, 'Remove unused JOB_STATUS and JOB_SCHEDULE_TIMESTAMP from JOB_REQUEST.', TO_DATE('01/26/2017', 'MM/DD/YYYY'));

COMMIT;