-- Table EBOOK_QA.EBOOK_DEFINITION
ALTER TABLE EBOOK_QA.EBOOK_DEFINITION
ADD NOTES varchar2(2048);
/

INSERT INTO EBOOK_QA.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (25, 'Added NOTES to EBOOK_DEFINITION', TO_DATE('05/24/2018', 'MM/DD/YYYY'));