/*
* Copyright 2011: Thomson Reuters Global Resources. All Rights Reserved.
* Proprietary and Confidential information of TRGR. Disclosure, Use or
* Reproduction without the written authorization of TRGR is prohibited
*/
package com.thomsonreuters.uscl.ereader;

/**
 * This class represents the names of well-known business keys used within the Spring Batch JobExecutionContext.
 * 
 * <p>The intent is that developers of steps specify the properties that they depend upon in this class, and 
 * use these names to retrieve those property values from the Spring Batch Job Execution Context.</p>
 * 
 * @author <a href="mailto:christopher.schwartz@thomsonreuters.com">Chris Schwartz</a> u0081674
 */
public class JobExecutionKey {
	
	/**
	 * The path from which to assemble the eBook from.
	 */
	public static final String EBOOK_DIRECTORY_PATH = "eBookDirectoryPath";
	
	/** Path to the destination directory for images files fetched from the Image Vertical REST web service. */
	public static final String EBOOK_IMAGE_DIRECTORY_PATH = "eBookImageDirectoryPath";
	
	/**
	 * The path to the assembled eBook on NAS.
	 */
	public static final String EBOOK_FILE_PATH = "eBookFilePath";
	
	/**
	 * The path to the Novus gathered XML documents for this eBook on NAS.
	 */
	public static final String EBOOK_GATHER_DOCS_PATH = "eBookGatherDocsPath";
	
	/**
	 * Path to the root destination directory for images files fetched from the Image Vertical REST web service.
	 * E.g. "/nas/ebookbuilder/data/<yyyyMMdd>/<titleId>/<jobInstanceId>/Gather/Images"
	 */
	public static final String EBOOK_GATHER_IMAGE_DIR_PATH = "eBookGatherImageDirPath";
	/**
	 * E.g. <eBookGatherImageDirPath>/Static
	 */
	public static final String EBOOK_GATHER_IMAGE_STATIC_DIR_PATH = "eBookGatherStaticImageDirPath";
	/**
	 * E.g. <eBookGatherImageDirPath>/Dynamic
	 */
	public static final String EBOOK_GATHER_IMAGE_DYNAMIC_DIR_PATH = "eBookGatherDynamicImageDirPath";

	/**
	 * Path to the flat text file that contatins the list (one per line) of image GUID's that represent the physical
	 * images that will be inserted into the book. 
	 */
	public static final String GATHER_TOC_XML_PATH = "gatherTocXmlPath";
	
	/**
	 * Path to the flat text file that contatins the list (one per line) of image GUID's that represent the physical
	 * images that will be inserted into the book. 
	 */
	public static final String EBOOK_GATHER_IMAGE_GUIDS_FILE_PATH = "eBookGatherImageGuidsFilePath";
	
	/**
	 * The path to the intermediate files generated by the Format Transformer Service for this eBook on NAS.
	 */
	public static final String EBOOK_FORMAT_TRANSFORMED_PATH = "eBookFormatTransformedPath";
	
	/**
	 * The path to the intermediate files generated by the Format HTML Wrapper Service for this eBook on NAS.
	 */
	public static final String EBOOK_FORMAT_HTML_WRAPPER_PATH = "eBookFormatHtmlWrapperPath";
	
	/**
	 * The path to the documents that are to be included in the published book. 
	 * 
	 * <em>The last step of format is responsible for setting this property.</em>
	 */
	public static final String FORMAT_DOCUMENTS_READY_DIRECTORY_PATH = "formatDocumentsReadyDirectoryPath";
	
	/**
	 * The number of documents that were initially retrieved from Novus, used as a sanity check after many SpringBatch steps.
	 */
	public static final String EBOOK_STATS_DOC_COUNT = "eBookStatsDocCount";
	
	/**
	 * The file path to the cover art on NAS.
	 */
	public static final String COVER_ART_PATH = "coverArtPath";
	
	/**
	 * The manifest file that describes which static images are included in the eBook.
	 */
	public static final String STATIC_IMAGE_MANIFEST_PATH = "staticImageManifestPath";
	
	/**
	 * The path to title.xml within the assemble directory.  The GenerateTitleMetadata step writes the title metadata to this file.
	 */
	public static final String TITLE_XML_PATH = "titleXmlPath";
}
