-- The table used to persist authentication ticket objects that have been generated by the
-- Central Authentication Service (CAS).
-- See codes-security: JdbcTicketRegistry.java and its associated DAO.

CREATE TABLE CAS_TICKET_REGISTRY
(
	ID	VARCHAR2(400)	PRIMARY KEY,
	TICKET	BLOB		NOT NULL
)