INSERT INTO EBOOK_TEST.SCHEMA_VERSION (SCHEMA_VERSION, COMMENTS, CHANGE_DATE)
VALUES (4.2, 'Added KEYWORD_TYPE_CODES.IS_REQUIRED column. Added EBOOK_DEFINITION.IS_PILOT_BOOK column. Added EBOOK_AUDIT.IS_PILOT_BOOK column.', TO_DATE('04/30/2012', 'MM/DD/YYYY'));

COMMIT;

ALTER TABLE EBOOK_TEST.KEYWORD_TYPE_CODES
 ADD (IS_REQUIRED  CHAR(1 BYTE)  DEFAULT 'N');
 
ALTER TABLE EBOOK_TEST.EBOOK_DEFINITION
 ADD (IS_PILOT_BOOK  CHAR(1 BYTE));
 
ALTER TABLE EBOOK_TEST.EBOOK_AUDIT
 ADD (IS_PILOT_BOOK  CHAR(1 BYTE));