name: eBookGatherer-ci-deploy
  
on: 
  push:
    branches: [ "java*" ]
  workflow_dispatch:
    inputs:
      artifact_version:
        description: 'Version'
        required: true
        default: '2308.0.40'
      BAMS:
        description: 'Artifactory location'
        required: true
        default: 'BuildArtifacts/EditorialContent/EBookGatherer'
      SCMserver:
        description: 'Deployment Manager'
        required: true
        default: 'c851oatscmdfd.int.thomsonreuters.com'
      SCMusername:
        description: 'Server credential'
        required: true
        default: 'asadmin'


env:
  # Define git user email and name to be used for git commits
  GIT_USER_EMAIL: "actions@github.com"
  GIT_USER_NAME: "GitHub Actions"
  ENV_CONFIG_FILE: ".github/env-variables.txt"
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true


jobs:
 checkstyle:
    name: Deploy        
     
    runs-on: [self-hosted, C343URQSCMAHP-SCM-GEN1-BuildMachine]

    steps:

    - name: display war files
      shell: cmd
      run: |
        curl -u  ${{ secrets.SCM_JFROG_ACCOUNT_NAME }}:${{ secrets.SCM_JFROG_API_TOKEN }} https://tr1.jfrog.io/artifactory/generic-local/SCM-Publishing/BuildArtifacts/EditorialContent/EBookGatherer/${{github.event.inputs.artifact_version}}/eBookGatherer.war -o eBookGatherer.war
        ls -ltr
    - name: display war files
      run: |
        $username = 'ECOMQC\svcTFSNGService'
        $SCMpassword1 = Get-Content -Path 'D:\password\password.txt'
        $password = ConvertTo-SecureString -String $SCMpassword1 -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential($username,$password)
        net use I: /delete
        net use /persistent:yes I: \\cobaltreleaseqc.int.westgroup.com\cobaltreleaseqc$ $SCMpassword1 /USER:svcTFSNGService
        rmdir  I:\eBookGatherer\${{github.event.inputs.artifact_version}}
        mkdir  I:\eBookGatherer\${{github.event.inputs.artifact_version}}
        copy ${{ github.workspace }}\* I:\eBookGatherer\${{github.event.inputs.artifact_version}}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{github.event.inputs.SCMserver}}
        username: ${{github.event.inputs.SCMusername}}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: whoami
