name: eBookGatherer-feature-build
  
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'java-*'
      - 'main' 
      - 'hotfix*'
      - 'release/*'
    tags-ignore:
      - '**'
    paths-ignore:
      - '**'
      
env:
  # Define git user email and name to be used for git commits
  GIT_USER_EMAIL: "actions@github.com"
  GIT_USER_NAME: "GitHub Actions"
  ENV_CONFIG_FILE: ".github/env-variables.txt"
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true


jobs:
 checkstyle:
    name: Build        
     
    runs-on: windows-latest
    #runs-on: [self-hosted]   
    permissions: write-all

    steps:
    - name: Grant permission for long paths
      run:  git config --system core.longpaths true

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
       java-version: '8'
       distribution: 'corretto'
       cache: gradle
     
    - name: Grant execute permission for gradlew wrapper
      run: chmod +x gradlew
   
    - name: CI Build for ebookGatherer with Gradle
      run: ./gradlew  -Dhttps.protocols=TLSv1.2 -Dorg.gradle.daemon=false -Dhttps.proxyPort=80 --stacktrace eBookGatherer:build -x test
      shell: cmd 
      
    - name: display war files
      run: |
        dir ebookGatherer\build\libs\
        tree
      shell: cmd
