# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
        - 'ebook_ebook-publishing/ebookManager/.*'
        - 'ebook_ebook-publishing/ebookStatic/.*'
        - 'ebook_ebook-publishing/ebookStylesheets/.*'
        - 'ebook_ebook-publishing/ebookGenerator/.*'
        - 'ebook_ebook-publishing/gradle/.*'
        - 'ebook_ebook-publishing/settings.gradle'
        - 'ebook_ebook-publishing/gradlew.bat'
        - 'ebook_ebook-publishing/.gitattributes'
        - 'ebook_ebook-publishing/.gitignore'
        - 'ebook_ebook-publishing/assetinfo.json'
        - 'ebook_ebook-publishing/build.gradle'
        - 'ebook_ebook-publishing/checkStyleConfig.xml'
        - 'ebook_ebook-publishing/gradlew'
      
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
        - 'ebook_ebook-publishing/ebookManager/.*'
        - 'ebook_ebook-publishing/ebookStatic/.*'
        - 'ebook_ebook-publishing/ebookStylesheets/.*'
        - 'ebook_ebook-publishing/ebookGenerator/.*'
        - 'ebook_ebook-publishing/gradle/.*'
        - 'ebook_ebook-publishing/settings.gradle'
        - 'ebook_ebook-publishing/gradlew.bat'
        - 'ebook_ebook-publishing/.gitattributes'
        - 'ebook_ebook-publishing/.gitignore'
        - 'ebook_ebook-publishing/assetinfo.json'
        - 'ebook_ebook-publishing/build.gradle'
        - 'ebook_ebook-publishing/checkStyleConfig.xml'
        - 'ebook_ebook-publishing/gradlew'

permissions:
  contents: read

jobs:
 checkstyle:
    name: runner / checkstyle        
     
    runs-on: windows-latest

    steps:
    - name: Grant permission for long paths
      run:  git config --system core.longpaths true
      
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8.0_202
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.202'
        distribution: 'adopt'
        cache: gradle
  
   
   
    - name: Output Run Number
      run: echo ${{ github.run_number }}
           echo "VERSION_NUMBER=0.0.0.${{ github.run_number }}"   
     
    - name: Grant execute permission for gradlew wrapper
      run: chmod +x gradlew
   
    - name: CI Build for ebookGatherer with Gradle
      run: ./gradlew  -Dhttps.protocols=TLSv1.2 -Dhttps.proxyHost=webproxy.int.westgroup.com -Dorg.gradle.daemon=false -Dhttps.proxyPort=80 --stacktrace eBookGatherer:build -x test
      shell: cmd 
      
    - name: display war files
      run: dir ebookGatherer\build\libs\
      shell: cmd
  
    - name: CI Build for ebookGenerator with Gradle
      run: .\gradlew -Dskip.tests=true -Dhttps.protocols=TLSv1.2 -Dhttps.proxyHost=webproxy.int.westgroup.com -Dorg.gradle.daemon=false -Dhttps.proxyPort=80 ebookGenerator:build -x test
      shell: cmd 
     
    - name: CI Build for ebookManager with Gradle
      run: .\gradlew -Dskip.tests=true -Dhttps.protocols=TLSv1.2 -Dhttps.proxyHost=webproxy.int.westgroup.com -Dorg.gradle.daemon=false -Dhttps.proxyPort=80 ebookManager:build -x test
      shell: cmd 
       
    - name: display war files
      run: dir ebookGenerator\build\libs\
      shell: cmd
