# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
        - 'ebook_ebook-publishing/ebookManager/.*'
        - 'ebook_ebook-publishing/ebookStatic/.*'
        - 'ebook_ebook-publishing/ebookStylesheets/.*'
        - 'ebook_ebook-publishing/ebookGenerator/.*'
        - 'ebook_ebook-publishing/gradle/.*'
        - 'ebook_ebook-publishing/settings.gradle'
        - 'ebook_ebook-publishing/gradlew.bat'
        - 'ebook_ebook-publishing/.gitattributes'
        - 'ebook_ebook-publishing/.gitignore'
        - 'ebook_ebook-publishing/assetinfo.json'
        - 'ebook_ebook-publishing/build.gradle'
        - 'ebook_ebook-publishing/checkStyleConfig.xml'
        - 'ebook_ebook-publishing/gradlew'
      
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
        - 'ebook_ebook-publishing/ebookManager/.*'
        - 'ebook_ebook-publishing/ebookStatic/.*'
        - 'ebook_ebook-publishing/ebookStylesheets/.*'
        - 'ebook_ebook-publishing/ebookGenerator/.*'
        - 'ebook_ebook-publishing/gradle/.*'
        - 'ebook_ebook-publishing/settings.gradle'
        - 'ebook_ebook-publishing/gradlew.bat'
        - 'ebook_ebook-publishing/.gitattributes'
        - 'ebook_ebook-publishing/.gitignore'
        - 'ebook_ebook-publishing/assetinfo.json'
        - 'ebook_ebook-publishing/build.gradle'
        - 'ebook_ebook-publishing/checkStyleConfig.xml'
        - 'ebook_ebook-publishing/gradlew'

permissions:
  contents: read

jobs:
           
   build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8.0_202
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.202'
        distribution: 'adopt'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B verify checkstyle:checkstyle
    - uses: jwgmeligmeyling/checkstyle-github-action@master
      with:
        path: '**/checkStyleConfig.xml'
   
    - name: Output Run Number
      run: echo ${{ github.run_number }}
           echo "VERSION_NUMBER=0.0.0.${{ github.run_number }}"   
     
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
   
    - name: Build with Gradle
      run: ./gradlew  -Dhttps.protocols=TLSv1.2 -Dhttps.proxyHost=webproxy.int.westgroup.com -Dorg.gradle.daemon=false -Dhttps.proxyPort=80  eBookGatherer:build
        
  
